name = "cruelty-check"
compatibility_date = "2025-09-11"

[[d1_databases]]
binding = "DATABASE"
database_name = "cruelty_check"
database_id = "4019788c-c882-45bf-b6e4-8ab9d60243fa"
migrations_dir = "migrations"
