-- Migration number: 0001 	 2025-09-11T10:12:01.618Z

CREATE TABLE Brands (
  "ID" INTEGER NOT NULL,
  "Name" TEXT NOT NULL,
  "Parent_ID" INTEGER NOT NULL,
  "Cruelty_Free" INTEGER NOT NULL,
  "B_Corp" INTEGER NOT NULL,
  "Fair_Trade" INTEGER NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE Products (
  "ID" INTEGER NOT NULL,
  "Name" TEXT NOT NULL,
  "Brand_ID" INTEGER NOT NULL,
  "Is_Vegan" INTEGER NOT NULL,
  "Image" TEXT,
  PRIMARY KEY ("ID")
);
